# Generated by Django 5.1 on 2024-09-02 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0002_rename_comosition_medicine_composition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='batches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('manufacturing_date', models.CharField(max_length=50)),
                ('expiry_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
            ],
        ),
    ]
