# Generated by Django 5.1 on 2024-08-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('dosage_form', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.CharField(max_length=50)),
                ('comosition', models.CharField(max_length=50)),
                ('indications', models.CharField(max_length=50)),
                ('contraindications', models.CharField(max_length=50)),
                ('side_effects', models.CharField(max_length=50)),
                ('barcode', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
